// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNd-ejUMPlRaCFe6DJs6oY6k-Flz_Dtlg',
    appId: '1:492474119544:web:c7c5243664905a26c1c48d',
    messagingSenderId: '492474119544',
    projectId: 'sooho-choi',
    authDomain: 'sooho-choi.firebaseapp.com',
    storageBucket: 'sooho-choi.firebasestorage.app',
    measurementId: 'G-1ENWLKEWM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkf_6krZQk_nfgPJRIk4mKTLaBAIystbE',
    appId: '1:492474119544:android:2afa6510f03ad7b8c1c48d',
    messagingSenderId: '492474119544',
    projectId: 'sooho-choi',
    storageBucket: 'sooho-choi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSXLH5yytWSIUHijIolvPpQaVIXvlL634',
    appId: '1:492474119544:ios:5bc8a02edbb321d0c1c48d',
    messagingSenderId: '492474119544',
    projectId: 'sooho-choi',
    storageBucket: 'sooho-choi.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
